### ISSUE TITLE
event data saved queries (3 of 3)

### ISSUE THREAD

**Issue by raprasad** [TwoRavens/TwoRavens#287]
### Tasks

- [x] Create TwoRavens eventdata dataset
- [ ] Add to settings:
  - [x] Dataverse token
  - [ ] mongo credentials
- [ ] celery task to do the following
  - [ ] run mongo query
  - [ ] store results to file
  - [ ] use dataverse api to write 3 files:
     - [ ] data file
     - [ ] query used for mongo
     - [ ] README describing other 2 files

**Comment by raprasad** [comment]
Notes:

- **Dataverse add file API**: https://gist.github.com/raprasad/044d455cb6a09b9a0f965e08dd564098
- **Dataset to use**: https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/SJWX4S
   - **persistentId**: `doi:10.7910/DVN/SJWX4S`

**Comment by raprasad** [comment]
- [ ] save Dataverse success responses

### API endpoint triggered

1. retrieve EventDataSavedQuery
1. if success: create `ArchiveQueryJob`
1. store results in ArchiveQueryJob
   - if `is_success` is False -> message is error message for user
   -  if `is_success` is True -> 
       - store the Dataverse response in "dataverse_response"
       - `archive_url` - default is "blank", 
           - construct url similar to: `https://dataverse.harvard.edu/file.xhtml?fileId=3085004`

**Comment by raprasad** [comment]
For adding files to Dataverse, there are 2 to 3 api steps:
- [x] (1) add the file to the dataset (done)
- [ ] (2) publish the dataset. 
   - this will make the file accessible to non-logged in users and allot a file DOI
   - See http://guides.dataverse.org/en/latest/api/native-api.html#publish-a-dataset
- [ ] (3) if needed, make an additional call to get the FILE doi and construct a new url to the Dataverse file page.
   - see "List Files in a Dataset" - http://guides.dataverse.org/en/latest/api/native-api.html#list-files-in-a-dataset
    - May need to use the file `id` returned from step (1) to find the DOI in the results

**Comment by raprasad** [comment]
Mongo reading is moved to another issue....
