### ISSUE TITLE
eval checklist

### ISSUE THREAD

**Issue by raprasad** [TwoRavens/TwoRavens#623]
- [x] (1) `Fitted vs. Actuals for predicting ${problem.targets[0]}`
- [x] (2) Pull pipeline model out into solutions table
- [x] (3) Steps flowchart sizing
- [x] (4) add target to results problems table
- [x] (5) download peek data
- [x] (6) sorting of pipeline table
- [x] (7) add target to results solutions table
- [x] (8) confusion matrix after augment (edited) 
- [x] (9) prompt to save workspace before augment

**Comment by raprasad** [comment]
- [ ] (10) task 1 submission 
    - Make Submit Problem description work
    - [Wiki](https://datadrivendiscovery.org/wiki/display/gov/2018+06+Summer+2018+Evaluation+Plan#id-201806Summer2018EvaluationPlan-AdditionalTask1Metric:MeaningfulProblems)   (Vito to confirm with Brian)
      - Table 5.2.1 and 5.1.3

**Comment by Shoeboxam** [comment]
- [ ] ingest of mongo should not mix numeric types
- [ ] click on solved problem, should not warn about existing problem
- [ ] scores not appearing
- [ ] solved problem table below current problem
- [ ] extra variables listed under plots in explore mode
- [ ] default plot for continuous data is incorrectly sized
- [ ] explore incorrectly sized box plot
- [ ] disable rookSolver again
- [ ] error when switching datasets via TA2 restart
- [ ] rook restarting, removing callsolver and caret should solve this

**Comment by Shoeboxam** [comment]
- [ ] i was unable to load ACLED, which is number 30 in my configs. it said there was not a config for this
- [ ] i initially started the ta2 with the baseball data, and then shut it down and went to switch to the popular kids data, which is number 24. however, the baseball data loaded in the browser. after i shut every terminal down, and deleted the test_setup_local, i was able to load the popular kids data
- [ ] in our meeting we talked about the description of the dataset. eventually, we want to add an “automated codebook” which describes the dataset, we did some work on this last summer (https://github.com/TwoRavens/metadata), and Mike mentioned using a piece from psi for this. this would be a static reference html/pdf that opens in a new tab. for now, we should add the basic structure to get a new tab, and just add the  “description” as text in that new tab. this can grow into the automated codebook
- [ ] after loading and click results, we need some type of movement/ladda on the page to let the user know that the back-end is working on the problem
- [ ] we should select a solution by default. either the first, or the best performing, i don’t think it matters much, but we need to have one selected by default
- [ ] the confusion matrix says “pipeline undefined” but it should say the pipeline number
- [ ] in Visualize Pipeline, the pipeline id is a number that does not match the pipeline number in the left panel. those numbers should match or the pipeline id is Visualize Pipeline could be dropped
- [ ] in the left panel, the “Score” should have the metric labeled, so instead of “Score” it should say “F1” for example
- [ ] if i click back to Models, and then select a new discovered problem and click results, it says “another problem is still being solved”. Raman suggested writing to Brown, because it seems that their TA2 is not listening to our request to stop the search
- [ ] Mike mentioned that this is fixed in the latest branch (to be pushed soon), but after clicking back to Model and a new Discovered Problem, I was not able to get back to my results page at all
- [ ] in addition to the automated codebook, which is a longer term piece of this project, we talked about a few things to help the user interpret and explore the results. (a) a little function to automatically identify interesting things in the results. for example, given 2 confusion matrices, a function could tell us which classes each pipeline is best at predicting and if which pipeline is better at which class
- [ ] also mentioned a tool for exploration where we click on a factor for the confusion matrix, and select a metric, and that factor-metric combination is recomputed for all pipelines
- [ ] Mike mentioned a tooltip where a mouseover on the confusion matrix provides some text that describes what this box is telling us
- [ ] we talked about rook automatically shutting down---eventually we need to drop rook altogether and convert those rook apps to something else
- [ ] can we rewrite this? https://github.com/TwoRavens/TwoRavens/blob/develop/assets/app/index.js#L573-L577

**Comment by Shoeboxam** [comment]
- [ ] i keep losing the variable list in left panel, it’s going black when i move cursor in and out of pebbles. it comes back if i click variables button in left panel
- [ ]  it was very easy to find the save buttons, but i could not find the load button. i was looking in the same place as save, but then realized it was triggered when i click the id at the top. i think we should just add a “load” button right next to “save”, and disable that functionality at the top (or just mirror the same functionality as load button)
- [ ]  i am unable to link a new pebble to the target variable, but i can add it to the predictor set
- [ ]  if i load a ws on a problem with a subset, the number of records stays the same. for example, i should have 111 records in for this problem, but it says i have 1073. however, it does look like the distributions are correct (drawn for 111 obs), it’s just that the number of records is not updated. also, if i open the data in a new window, i see all the data, not the subset. 
- [ ] save, save as, load, and revert functionality is *awesome*. it all worked exactly as i’d expect it to
- [ ]  i was not able to delete a problem or successfully complete a transform (I tried a couple different transform manipulations)
- [ ]  link sharing does not work as intended. i was working in Chrome and turned link sharing on, copied the url into Safari, and got this message in Safari:
- [ ]  there seems to be an issue with the discovered problems. if i click a problem, it increments, for example says i’m working on problem 28. i then make some changes, and now problem 28 looks good. i click off problem 28, and that problem disappears so i have lost my work

**Comment by Shoeboxam** [comment]
- [ ] empirical first differences
- [ ] ICE plots

**Comment by raprasad** [comment]
- [ ] remove "remnant" in code where only used the 1st target in the problemDoc

**Comment by Shoeboxam** [comment]
- [ ] rightpanel lock hopscotch
- [ ] force rightpanel lock if solved problem

**Comment by tercer** [comment]
- [ ] Panel closes but doesn't remove buttons:
<img width="50" alt="Screen Shot 2019-07-08 at 9 07 21 PM" src="https://user-images.githubusercontent.com/2085037/60907578-bb88a280-a22e-11e9-8231-8cc71ab06937.png">
<img width="99" alt="Screen Shot 2019-07-08 at 9 07 05 PM" src="https://user-images.githubusercontent.com/2085037/60907581-bd526600-a22e-11e9-9268-2a00199f2449.png">

**Comment by vjdorazio** [comment]
for SEMI datasets (1053_jm1, 1459_artificial_characters, 155_pokerhand, 1217_click_prediction_small), i'm seeing similar errors. this screenshot is one of the errors in javascript console on load:

<img width="1277" alt="Screen Shot 2019-07-18 at 2 47 32 PM" src="https://user-images.githubusercontent.com/3503987/61487243-0317d880-a96b-11e9-9eba-1d2538eb21e3.png">

and this is the TA2 output (brown) after click "Results":
 
<img width="574" alt="Screen Shot 2019-07-18 at 2 42 24 PM" src="https://user-images.githubusercontent.com/3503987/61487165-cc41c280-a96a-11e9-8590-5515a7245fdb.png">
 
the TA2 error might be because some of the values in the target variable are undefined, since this is a semi-supervised problem.
