### ISSUE TITLE
Multi-user testing checklist

### ISSUE THREAD

**Issue by raprasad** [TwoRavens/TwoRavens#710]
- [x] component / L2 activity spreadsheet
- [x] remove HU/UTD from site as well as help materials
- [x] hide Datamart Tab
- [x] ** run on GCE so that datasets can be switched.  This is one that will need some deployment changes / most work.  See #713 
- [x] datasets to use:
   - [x] baseball
   - [x] incarceration
   - [x] immigration policy
- [x] logging, distinguish logs and app instances by similar terms. colors, animals, etc
- [x] potential logging updates:
   -  frequently write to file on shared disk space OR
   -  possibly send log info via http on a separate, continuously running service
